name: CVE Dependency Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan:
    name: Scan for CVEs in Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: .
          format: 'template'
          template: "@html.tpl"
          output: "cve-report.html"


      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cve-report
          path: cve-report.html

  deploy:
    name: Deploy HTML Report to Web Server
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Import HTML Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: cve-report

      - name: Copy files via SCP action
        uses: appleboy/scp-action@master
        with:
            host: dhbw.hoenle.xyz
            username: group2
            key: ${{ secrets.PRIVATE_SSH }}
            source: "./cve-report.html"
            target: "/var/www/group2/"
