name: Meine super duper Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

env:
  GO_VERSION: "1.19"
  NODE_VERSION: "16"

jobs:
    checkout:
        name: Checkout
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

    build:
        name: Build
        needs: checkout
        runs-on: ubuntu-latest
        steps:

            - name: Install go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ env.GO_VERSION }}
                
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Build frontend
              working-directory: ./frontend
              run: |
                npm ci
                npx ng build
                mkdir -p ../backend/cmd/strichliste/frontendDist
                cp -r dist/frontend/browser ../backend/cmd/strichliste/frontendDist

    tests:
        name: Tests
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              working-directory: ./backend
              run: go test ./...
