name: Meine super duper Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ env.GO_VERSION }}
            
            - name: Run tests
              working-directory: ./backend
              run: go test ./...